apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::787089741326:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:masters\n  rolearn: arn:aws:iam::787089741326:role/UdacityFlaskDeployCBKubectlRole\n  username: build \n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-11-01T19:42:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "29134"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2265037b-47c6-4b1f-bf1f-34182f377946
